# Generated by Django 5.0.2 on 2025-03-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('licence', 'Licence (Bac+3)'), ('master', 'Master (Bac+5)'), ('doctorat', 'Doctorat (Bac+8)'), ('bts', 'BTS'), ('dut', 'DUT'), ('ingenieur', "Diplôme d'Ingénieur"), ('other', 'Autre')], max_length=20)),
                ('field', models.CharField(choices=[('science', 'Sciences'), ('engineering', 'Ingénierie'), ('business', 'Commerce'), ('law', 'Droit'), ('medicine', 'Médecine'), ('arts', 'Arts et Lettres'), ('social', 'Sciences Sociales'), ('education', 'Éducation'), ('other', 'Autre')], max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('student_count', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
