# Generated by Django 5.0.2 on 2025-03-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='program',
            old_name='level',
            new_name='degree_level',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='field',
        ),
        migrations.RemoveField(
            model_name='program',
            name='image',
        ),
        migrations.RemoveField(
            model_name='program',
            name='status',
        ),
        migrations.RemoveField(
            model_name='program',
            name='student_count',
        ),
        migrations.AddField(
            model_name='program',
            name='admission_requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='language',
            field=models.CharField(default='Français', max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='tuition_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
