# Generated by Django 5.0.2 on 2025-04-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='career_opportunities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='evaluation_methods',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='internship_opportunities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='research_opportunities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='student_life',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='teaching_methods',
            field=models.TextField(blank=True),
        ),
    ]
