# Generated by Django 5.0.2 on 2025-03-08 09:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='employment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='facilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='university',
            name='international_partnerships',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='university',
            name='research_focus',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='university',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='university',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='universitie_search__0b12bd_gin'),
        ),
    ]
