# Generated by Django 5.0.2 on 2025-03-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_employment_rate_university_facilities_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='university',
            name='universitie_search__0b12bd_gin',
        ),
        migrations.RemoveField(
            model_name='university',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='university',
            name='facilities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='university',
            name='international_partnerships',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='university',
            name='research_focus',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='university',
            name='specialties',
            field=models.JSONField(default=list),
        ),
    ]
