# Generated by Django 5.0.2 on 2025-03-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_remove_university_universitie_search__0b12bd_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='academic_calendar',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='university',
            name='admission_requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='university',
            name='contact_info',
            field=models.JSONField(default=dict),
        ),
    ]
