# Generated by Django 5.0.2 on 2025-03-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('engineering', 'Ingénierie'), ('science', 'Sciences'), ('business', 'Commerce'), ('arts', 'Arts et Lettres'), ('social', 'Sciences Sociales'), ('law', 'Droit'), ('medicine', 'Médecine'), ('education', 'Éducation')], max_length=20)),
                ('compatibility', models.IntegerField()),
            ],
            options={
                'ordering': ['-compatibility'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('engineering_weight', models.IntegerField(default=0)),
                ('science_weight', models.IntegerField(default=0)),
                ('business_weight', models.IntegerField(default=0)),
                ('arts_weight', models.IntegerField(default=0)),
                ('social_weight', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orientation_tests.question')),
            ],
        ),
    ]
