# Generated by Django 5.0.2 on 2025-04-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='transcript_files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
